/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkApiRouteImport } from './routes/work-api'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as PipelineStatusApiRouteImport } from './routes/pipeline-status-api'
import { Route as PipelineEventsApiRouteImport } from './routes/pipeline-events-api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantIndexRouteImport } from './routes/plant.index'
import { Route as WorkApiReplayRouteImport } from './routes/work-api.replay'
import { Route as WorkApiMangaProcessRouteImport } from './routes/work-api.manga-process'
import { Route as WorkApiIngestRouteImport } from './routes/work-api.ingest'
import { Route as WorkApiClearAllRouteImport } from './routes/work-api.clear-all'
import { Route as PlantWavesRouteImport } from './routes/plant.waves'
import { Route as PlantPerformanceRouteImport } from './routes/plant.performance'
import { Route as PlantHdbRouteImport } from './routes/plant.hdb'
import { Route as PlantExplorerRouteImport } from './routes/plant.explorer'
import { Route as PlantAppRouteImport } from './routes/plant.app'
import { Route as ApiWorkRouteImport } from './routes/api.work'
import { Route as ApiLanceRouteImport } from './routes/api.lance'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ApiCodex4RouteImport } from './routes/api.codex4'
import { Route as PlantSuttaJobIdRouteImport } from './routes/plant.sutta.$jobId'
import { Route as ApiMangaImageVolumePanelIdRouteImport } from './routes/api.manga.image.$volume.$panelId'

const WorkApiRoute = WorkApiRouteImport.update({
  id: '/work-api',
  path: '/work-api',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineStatusApiRoute = PipelineStatusApiRouteImport.update({
  id: '/pipeline-status-api',
  path: '/pipeline-status-api',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineEventsApiRoute = PipelineEventsApiRouteImport.update({
  id: '/pipeline-events-api',
  path: '/pipeline-events-api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIndexRoute = PlantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlantRoute,
} as any)
const WorkApiReplayRoute = WorkApiReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => WorkApiRoute,
} as any)
const WorkApiMangaProcessRoute = WorkApiMangaProcessRouteImport.update({
  id: '/manga-process',
  path: '/manga-process',
  getParentRoute: () => WorkApiRoute,
} as any)
const WorkApiIngestRoute = WorkApiIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => WorkApiRoute,
} as any)
const WorkApiClearAllRoute = WorkApiClearAllRouteImport.update({
  id: '/clear-all',
  path: '/clear-all',
  getParentRoute: () => WorkApiRoute,
} as any)
const PlantWavesRoute = PlantWavesRouteImport.update({
  id: '/waves',
  path: '/waves',
  getParentRoute: () => PlantRoute,
} as any)
const PlantPerformanceRoute = PlantPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PlantRoute,
} as any)
const PlantHdbRoute = PlantHdbRouteImport.update({
  id: '/hdb',
  path: '/hdb',
  getParentRoute: () => PlantRoute,
} as any)
const PlantExplorerRoute = PlantExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => PlantRoute,
} as any)
const PlantAppRoute = PlantAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => PlantRoute,
} as any)
const ApiWorkRoute = ApiWorkRouteImport.update({
  id: '/api/work',
  path: '/api/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLanceRoute = ApiLanceRouteImport.update({
  id: '/api/lance',
  path: '/api/lance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodex4Route = ApiCodex4RouteImport.update({
  id: '/api/codex4',
  path: '/api/codex4',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantSuttaJobIdRoute = PlantSuttaJobIdRouteImport.update({
  id: '/sutta/$jobId',
  path: '/sutta/$jobId',
  getParentRoute: () => PlantRoute,
} as any)
const ApiMangaImageVolumePanelIdRoute =
  ApiMangaImageVolumePanelIdRouteImport.update({
    id: '/api/manga/image/$volume/$panelId',
    path: '/api/manga/image/$volume/$panelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline-events-api': typeof PipelineEventsApiRoute
  '/pipeline-status-api': typeof PipelineStatusApiRoute
  '/plant': typeof PlantRouteWithChildren
  '/work-api': typeof WorkApiRouteWithChildren
  '/api/codex4': typeof ApiCodex4Route
  '/api/events': typeof ApiEventsRoute
  '/api/lance': typeof ApiLanceRoute
  '/api/work': typeof ApiWorkRoute
  '/plant/app': typeof PlantAppRoute
  '/plant/explorer': typeof PlantExplorerRoute
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/performance': typeof PlantPerformanceRoute
  '/plant/waves': typeof PlantWavesRoute
  '/work-api/clear-all': typeof WorkApiClearAllRoute
  '/work-api/ingest': typeof WorkApiIngestRoute
  '/work-api/manga-process': typeof WorkApiMangaProcessRoute
  '/work-api/replay': typeof WorkApiReplayRoute
  '/plant/': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
  '/api/manga/image/$volume/$panelId': typeof ApiMangaImageVolumePanelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline-events-api': typeof PipelineEventsApiRoute
  '/pipeline-status-api': typeof PipelineStatusApiRoute
  '/work-api': typeof WorkApiRouteWithChildren
  '/api/codex4': typeof ApiCodex4Route
  '/api/events': typeof ApiEventsRoute
  '/api/lance': typeof ApiLanceRoute
  '/api/work': typeof ApiWorkRoute
  '/plant/app': typeof PlantAppRoute
  '/plant/explorer': typeof PlantExplorerRoute
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/performance': typeof PlantPerformanceRoute
  '/plant/waves': typeof PlantWavesRoute
  '/work-api/clear-all': typeof WorkApiClearAllRoute
  '/work-api/ingest': typeof WorkApiIngestRoute
  '/work-api/manga-process': typeof WorkApiMangaProcessRoute
  '/work-api/replay': typeof WorkApiReplayRoute
  '/plant': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
  '/api/manga/image/$volume/$panelId': typeof ApiMangaImageVolumePanelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipeline-events-api': typeof PipelineEventsApiRoute
  '/pipeline-status-api': typeof PipelineStatusApiRoute
  '/plant': typeof PlantRouteWithChildren
  '/work-api': typeof WorkApiRouteWithChildren
  '/api/codex4': typeof ApiCodex4Route
  '/api/events': typeof ApiEventsRoute
  '/api/lance': typeof ApiLanceRoute
  '/api/work': typeof ApiWorkRoute
  '/plant/app': typeof PlantAppRoute
  '/plant/explorer': typeof PlantExplorerRoute
  '/plant/hdb': typeof PlantHdbRoute
  '/plant/performance': typeof PlantPerformanceRoute
  '/plant/waves': typeof PlantWavesRoute
  '/work-api/clear-all': typeof WorkApiClearAllRoute
  '/work-api/ingest': typeof WorkApiIngestRoute
  '/work-api/manga-process': typeof WorkApiMangaProcessRoute
  '/work-api/replay': typeof WorkApiReplayRoute
  '/plant/': typeof PlantIndexRoute
  '/plant/sutta/$jobId': typeof PlantSuttaJobIdRoute
  '/api/manga/image/$volume/$panelId': typeof ApiMangaImageVolumePanelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pipeline-events-api'
    | '/pipeline-status-api'
    | '/plant'
    | '/work-api'
    | '/api/codex4'
    | '/api/events'
    | '/api/lance'
    | '/api/work'
    | '/plant/app'
    | '/plant/explorer'
    | '/plant/hdb'
    | '/plant/performance'
    | '/plant/waves'
    | '/work-api/clear-all'
    | '/work-api/ingest'
    | '/work-api/manga-process'
    | '/work-api/replay'
    | '/plant/'
    | '/plant/sutta/$jobId'
    | '/api/manga/image/$volume/$panelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pipeline-events-api'
    | '/pipeline-status-api'
    | '/work-api'
    | '/api/codex4'
    | '/api/events'
    | '/api/lance'
    | '/api/work'
    | '/plant/app'
    | '/plant/explorer'
    | '/plant/hdb'
    | '/plant/performance'
    | '/plant/waves'
    | '/work-api/clear-all'
    | '/work-api/ingest'
    | '/work-api/manga-process'
    | '/work-api/replay'
    | '/plant'
    | '/plant/sutta/$jobId'
    | '/api/manga/image/$volume/$panelId'
  id:
    | '__root__'
    | '/'
    | '/pipeline-events-api'
    | '/pipeline-status-api'
    | '/plant'
    | '/work-api'
    | '/api/codex4'
    | '/api/events'
    | '/api/lance'
    | '/api/work'
    | '/plant/app'
    | '/plant/explorer'
    | '/plant/hdb'
    | '/plant/performance'
    | '/plant/waves'
    | '/work-api/clear-all'
    | '/work-api/ingest'
    | '/work-api/manga-process'
    | '/work-api/replay'
    | '/plant/'
    | '/plant/sutta/$jobId'
    | '/api/manga/image/$volume/$panelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelineEventsApiRoute: typeof PipelineEventsApiRoute
  PipelineStatusApiRoute: typeof PipelineStatusApiRoute
  PlantRoute: typeof PlantRouteWithChildren
  WorkApiRoute: typeof WorkApiRouteWithChildren
  ApiCodex4Route: typeof ApiCodex4Route
  ApiEventsRoute: typeof ApiEventsRoute
  ApiLanceRoute: typeof ApiLanceRoute
  ApiWorkRoute: typeof ApiWorkRoute
  ApiMangaImageVolumePanelIdRoute: typeof ApiMangaImageVolumePanelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-api': {
      id: '/work-api'
      path: '/work-api'
      fullPath: '/work-api'
      preLoaderRoute: typeof WorkApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-status-api': {
      id: '/pipeline-status-api'
      path: '/pipeline-status-api'
      fullPath: '/pipeline-status-api'
      preLoaderRoute: typeof PipelineStatusApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-events-api': {
      id: '/pipeline-events-api'
      path: '/pipeline-events-api'
      fullPath: '/pipeline-events-api'
      preLoaderRoute: typeof PipelineEventsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/': {
      id: '/plant/'
      path: '/'
      fullPath: '/plant/'
      preLoaderRoute: typeof PlantIndexRouteImport
      parentRoute: typeof PlantRoute
    }
    '/work-api/replay': {
      id: '/work-api/replay'
      path: '/replay'
      fullPath: '/work-api/replay'
      preLoaderRoute: typeof WorkApiReplayRouteImport
      parentRoute: typeof WorkApiRoute
    }
    '/work-api/manga-process': {
      id: '/work-api/manga-process'
      path: '/manga-process'
      fullPath: '/work-api/manga-process'
      preLoaderRoute: typeof WorkApiMangaProcessRouteImport
      parentRoute: typeof WorkApiRoute
    }
    '/work-api/ingest': {
      id: '/work-api/ingest'
      path: '/ingest'
      fullPath: '/work-api/ingest'
      preLoaderRoute: typeof WorkApiIngestRouteImport
      parentRoute: typeof WorkApiRoute
    }
    '/work-api/clear-all': {
      id: '/work-api/clear-all'
      path: '/clear-all'
      fullPath: '/work-api/clear-all'
      preLoaderRoute: typeof WorkApiClearAllRouteImport
      parentRoute: typeof WorkApiRoute
    }
    '/plant/waves': {
      id: '/plant/waves'
      path: '/waves'
      fullPath: '/plant/waves'
      preLoaderRoute: typeof PlantWavesRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/performance': {
      id: '/plant/performance'
      path: '/performance'
      fullPath: '/plant/performance'
      preLoaderRoute: typeof PlantPerformanceRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/hdb': {
      id: '/plant/hdb'
      path: '/hdb'
      fullPath: '/plant/hdb'
      preLoaderRoute: typeof PlantHdbRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/explorer': {
      id: '/plant/explorer'
      path: '/explorer'
      fullPath: '/plant/explorer'
      preLoaderRoute: typeof PlantExplorerRouteImport
      parentRoute: typeof PlantRoute
    }
    '/plant/app': {
      id: '/plant/app'
      path: '/app'
      fullPath: '/plant/app'
      preLoaderRoute: typeof PlantAppRouteImport
      parentRoute: typeof PlantRoute
    }
    '/api/work': {
      id: '/api/work'
      path: '/api/work'
      fullPath: '/api/work'
      preLoaderRoute: typeof ApiWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lance': {
      id: '/api/lance'
      path: '/api/lance'
      fullPath: '/api/lance'
      preLoaderRoute: typeof ApiLanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex4': {
      id: '/api/codex4'
      path: '/api/codex4'
      fullPath: '/api/codex4'
      preLoaderRoute: typeof ApiCodex4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/sutta/$jobId': {
      id: '/plant/sutta/$jobId'
      path: '/sutta/$jobId'
      fullPath: '/plant/sutta/$jobId'
      preLoaderRoute: typeof PlantSuttaJobIdRouteImport
      parentRoute: typeof PlantRoute
    }
    '/api/manga/image/$volume/$panelId': {
      id: '/api/manga/image/$volume/$panelId'
      path: '/api/manga/image/$volume/$panelId'
      fullPath: '/api/manga/image/$volume/$panelId'
      preLoaderRoute: typeof ApiMangaImageVolumePanelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlantRouteChildren {
  PlantAppRoute: typeof PlantAppRoute
  PlantExplorerRoute: typeof PlantExplorerRoute
  PlantHdbRoute: typeof PlantHdbRoute
  PlantPerformanceRoute: typeof PlantPerformanceRoute
  PlantWavesRoute: typeof PlantWavesRoute
  PlantIndexRoute: typeof PlantIndexRoute
  PlantSuttaJobIdRoute: typeof PlantSuttaJobIdRoute
}

const PlantRouteChildren: PlantRouteChildren = {
  PlantAppRoute: PlantAppRoute,
  PlantExplorerRoute: PlantExplorerRoute,
  PlantHdbRoute: PlantHdbRoute,
  PlantPerformanceRoute: PlantPerformanceRoute,
  PlantWavesRoute: PlantWavesRoute,
  PlantIndexRoute: PlantIndexRoute,
  PlantSuttaJobIdRoute: PlantSuttaJobIdRoute,
}

const PlantRouteWithChildren = PlantRoute._addFileChildren(PlantRouteChildren)

interface WorkApiRouteChildren {
  WorkApiClearAllRoute: typeof WorkApiClearAllRoute
  WorkApiIngestRoute: typeof WorkApiIngestRoute
  WorkApiMangaProcessRoute: typeof WorkApiMangaProcessRoute
  WorkApiReplayRoute: typeof WorkApiReplayRoute
}

const WorkApiRouteChildren: WorkApiRouteChildren = {
  WorkApiClearAllRoute: WorkApiClearAllRoute,
  WorkApiIngestRoute: WorkApiIngestRoute,
  WorkApiMangaProcessRoute: WorkApiMangaProcessRoute,
  WorkApiReplayRoute: WorkApiReplayRoute,
}

const WorkApiRouteWithChildren =
  WorkApiRoute._addFileChildren(WorkApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelineEventsApiRoute: PipelineEventsApiRoute,
  PipelineStatusApiRoute: PipelineStatusApiRoute,
  PlantRoute: PlantRouteWithChildren,
  WorkApiRoute: WorkApiRouteWithChildren,
  ApiCodex4Route: ApiCodex4Route,
  ApiEventsRoute: ApiEventsRoute,
  ApiLanceRoute: ApiLanceRoute,
  ApiWorkRoute: ApiWorkRoute,
  ApiMangaImageVolumePanelIdRoute: ApiMangaImageVolumePanelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
