#!/usr/bin/env python3
import json
import argparse
import av
from pathlib import Path

try:
    from .utils import atomic_write_json
except (ImportError, ValueError):
    from utils import atomic_write_json

def merge_audio_files(input_paths, output_path):
    """Merges multiple MP3s into one using the 'av' library."""
    print(f"    -> Assembling: {output_path.name}")
    try:
        output_container = av.open(str(output_path), mode='w')
        output_stream = output_container.add_stream('mp3', rate=44100)

        for p in input_paths:
            if not Path(p).exists(): continue
            input_container = av.open(str(p))
            for frame in input_container.decode(audio=0):
                for packet in output_stream.encode(frame):
                    output_container.mux(packet)
            input_container.close()

        # Flush
        for packet in output_stream.encode():
            output_container.mux(packet)
        output_container.close()
        return True
    except Exception as e:
        print(f"    [!] Merge Error: {e}")
        return False

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pattern", type=str, default="AN *.json")
    args = ap.parse_args()

    root = Path(__file__).parent
    files = list(root.glob(args.pattern))

    for path in files:
        if "gt2Se9HmLEs" in path.name: continue
        with open(path, "r", encoding="utf-8") as f: data = json.load(f)

        audio_info = data.get("audio_ja")
        if not audio_info: continue

        vid = data.get("vid")
        sutta_id = data.get("sutta_id").replace(".", "_")

        # Paths to the clips generated by stage 22
        clips = [
            root / audio_info["sutta"],
            root / audio_info["commentary"],
            root / audio_info["mcq"]
        ]

        # The final unified file path (Alongside original audio)
        final_filename = f"{sutta_id}_ja_full.mp3"
        final_path = root / "assets" / vid / final_filename

        if merge_audio_files(clips, final_path):
            # Update JSON with the single 'Production' audio track
            data["audio_ja_full"] = f"assets/{vid}/{final_filename}"
            atomic_write_json(path, data)
            print(f"    [OK] Unified audio ready at: {final_filename}")

if __name__ == "__main__":
    main()
